### ISSUE TITLE
Language support?

### ISSUE THREAD

**Issue by Xaynder** [viezel/TiSocial.Framework#111]
Hello,

I'm using your module and it's working fine, the only problem is that the activityView is in english and my app is in french. I thought the module would automatically adjust to Ti.Platform.locale but apparently that's not the case.

Any workarounds?

Cheers,
Alex

**Comment by ludolphus** [comment]
Put this in your plist entry of tiapp.xml

~~~
            <dict>
                <key>CFBundleAllowMixedLocalizations</key>
                <string>true</string>
            </dict>
~~~

More complete example:
~~~
    <ios>
        <min-ios-ver>7.0</min-ios-ver>
        <plist>
            <dict>
                <key>CFBundleAllowMixedLocalizations</key>
                <string>true</string>
            </dict>
        </plist>
    </ios>
~~~

**Comment by Xaynder** [comment]
It works!
Amazing, thank you!
