### ISSUE TITLE
64bit self compile try

### ISSUE THREAD

**Issue by caspahouzer** [viezel/TiSocial.Framework#116]
I did it like announced here: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available/

and here

https://jira.appcelerator.org/browse/TIMOB-18065

But the architecture remains to "armv7 i386"

Do you/anyone have an idea?

**Comment by FokkeZB** [comment]
@viezel: https://github.com/viezel/TiSocial.Framework/commit/6683224e35f618435cd6aac550b24c4c25f71391#commitcomment-9217406

**Comment by caspahouzer** [comment]
So... the build.py was not correctly?

**Comment by viezel** [comment]
you did almost the right thing, but since some modules are very old, the default settings are not enough, you need to explicit show which arch you want:

https://github.com/viezel/TiSocial.Framework/commit/6683224e35f618435cd6aac550b24c4c25f71391#diff-47fcb586479148dd2bc04ee5ac19194eR277

**Comment by caspahouzer** [comment]
Thanks. I will have a try

**Comment by caspahouzer** [comment]
Which settings are this in xcode?

**Comment by viezel** [comment]
http://cl.ly/image/0I093V0G3M3n

**Comment by caspahouzer** [comment]
Got it. thanks for your help.

**Comment by viezel** [comment]
What matters is the archs.. Nvm the build.py.
