### ISSUE TITLE
iPad popover not appear in 1.7.8 with 3.5.0.GA

### ISSUE THREAD

**Issue by caspahouzer** [viezel/TiSocial.Framework#117]
~~~
var Social = require('dk.napp.social');
        var params = {
            removeIcons: "weibo,print,contact,camera,copy,twitter"
        };
//            params.text = 'share this thing';

       
        params.view = myBtn;
        Social.activityPopover(params);
~~~

This is my code. The popover does not show up in 1.7.8 AND 1.7.7. 

Tested from 1.7.4 to 1.7.6. All are working and showing the popover. But I can't tap beside the popover to hide it.

Maybe it is based on, that a popover needs a contentview? No error is shown in the logs.

**Comment by AppWerft** [comment]
I have compiled the module with SDK 3.5.0.GA and get the same issue. On iPad no popover appears.

**Comment by kchapelier** [comment]
I have the same issue with 1.7.7 on 3.4.0.GA

**Comment by caspahouzer** [comment]
Great! Thanks
