### ISSUE TITLE
facebook not showing status + image

### ISSUE THREAD

**Issue by alexandreshah** [viezel/TiSocial.Framework#132]
on iOS 8, with 3.5.1:

```
    var payload = {};
    payload.text = args.status;
    if (args.image){
        payload.image = args.image;
    }
    if(Social.isActivityViewSupported()){ //min iOS6 required
        if (Ti.Platform.osname == 'ipad') {
            payload.view = args.view;
            Social.activityPopover(payload);
        }else{
            Social.activityView(payload);
        }
           }
```

Only shows the image, not the text on facebook

**Comment by amurovsky** [comment]
I have the same issue, i guess its for the recent Facebook sdk update.

**Comment by HPieters** [comment]
Same problem here...

**Comment by e3bmo3ty** [comment]
any FIX ?

**Comment by skoften** [comment]
same problem...

**Comment by alan89** [comment]
Sounds like a bug, but not of this module. Check this discussion.

http://openradar.appspot.com/20709403

**Comment by caspahouzer** [comment]
So... nox fix until facebook changes their api

**Comment by hansemannn** [comment]
The native way is to use the Facebook Share API from ti.facebook if the facebook activity is selected. This is no module issue.
