### ISSUE TITLE
cant find module: ti.imagefactory for architecture x86_64

### ISSUE THREAD

**Issue by ghost** [viezel/TiSocial.Framework#141]
![image](https://cloud.githubusercontent.com/assets/13020023/8310942/0864fb62-19cb-11e5-9505-c64adda0b372.png)

**Comment by fcodebue** [comment]
I suppose problema is not only about ti.imagefactory but for all system. 2015 it's year of 64bit smartphone architetcture and so It's very important to have TI components works with it.
