### ISSUE TITLE
iPad popover on modal window

### ISSUE THREAD

**Issue by caspahouzer** [viezel/TiSocial.Framework#148]
If I try to show the popover view on a button in a modal window, I got the following message:

Warning: Attempt to present UIActivityViewController: 0x7e59da70  on TiRootViewController: 0x7aab9800 which is already presenting TiViewController: 0x78f4b460

**Comment by caspahouzer** [comment]
No one with this problem?

**Comment by enrique26** [comment]
this is because you trying to show the modal widget on a button; you have to add on a view element

**Comment by caspahouzer** [comment]
why not on a button? it worked already with buttons

**Comment by enrique26** [comment]
i had the same issue and that was my solution in that moment. still i dont know what is causing that problem

**Comment by caspahouzer** [comment]
But that works not, too. 
For iPad, I now have a self built popover with some sharing options.

**Comment by danielkscarmo** [comment]
Same problem here

**Comment by caspahouzer** [comment]
And no longer support as it seems :-(

**Comment by danielkscarmo** [comment]
My huge workaround was to replace all modal windows using this module on iPad, so on iPad I really need to open non-modal windows to present this module popover. I also needed to attach the popover to views, it was not possible to attach to buttons anymore :( .

**Comment by hansemannn** [comment]
@christianrockbryan Please check the latest [v1.8.4](https://github.com/viezel/TiSocial.Framework/blob/master/dist/dk.napp.social-iphone-1.8.4.zip) update and close this issue if its fixed.

**Comment by danielkscarmo** [comment]
v1.8.4 works on iPad modal window to me
