### ISSUE TITLE
Sharing crashes on iPad

### ISSUE THREAD

**Issue by christianrockbryan** [viezel/TiSocial.Framework#154]
I'm creating an iPad app where I am trying to share an image.  Here is my code:

   if(objSocial.isActivityViewSupported()){ 

		DebugPrint('Share Current Image (4.1) - Sharing supported - so far so good');
		DebugPrint('Share Current Image (4.1) - sImage='+sImage);

      objSocial.activityPopover({
          text: "Share Image"
          ,subject: "Share Image"
          ,image:sImage
          //removeIcons:"print,sms,copy,contact,camera,mail",
          ,view: btnShare //source button imgShare
      });
		
   } else {
       //implement fallback sharing..
		DebugPrint('Share Current Image (4.2) - sharing failed');

   }

The error I get when I run this is the following:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TiUIButtonProxy _viewForPresenting]: unrecognized selector sent to instance 0x13e0ac000'

I have tried using a button as the "view" parameter as well as an ImageView.  Both give me the same error.

I am using SDK 5.0.2 on an iPad only app.  Thanks!

**Comment by sobytes** [comment]
@christianrockbryan I am also getting this error on iPad 2 did you make any progress?

**Comment by christianrockbryan** [comment]
Unfortunately no.  I haven't tried it again since posting here, but I also have not heard any response on it.

**Comment by sobytes** [comment]
Ok thanks yes its definately crashing on a iPad Air 2 with the follow code.

~~~
var Social = require('dk.napp.social');
if (Social.isActivityViewSupported()) {
    if (Ti.Platform.osname == "ipad") {

        Social.activityPopover({
            view: $.openIpad,
            text: address,
            url: "http://example.com"
        });
    }
} else {

}
~~~

Ive also posted here 

https://community.appcelerator.com/topic/4005/dk-napp-social-social-crashing-on-ipad-air-2-cant-find-a-appcelerator-sharing-widget-that-works-for-all-ios-platforms

Hope someone can suggest a fix.

@christianrockbryan what was your solution did you use something else?

**Comment by caspahouzer** [comment]
There are several issues open for this:
https://github.com/viezel/TiSocial.Framework/issues/148
https://github.com/viezel/TiSocial.Framework/issues/149
https://github.com/viezel/TiSocial.Framework/issues/153

@viezel a solution for that would be really nice. Or did you stopped working on that completely?

**Comment by viezel** [comment]
Im not working on it. I believe Appc should step up and implement Social and Account Framework into the core.

**Comment by caspahouzer** [comment]
Thanks

**Comment by hansemannn** [comment]
@christianrockbryan Please check the latest [v1.8.4](https://github.com/viezel/TiSocial.Framework/blob/master/dist/dk.napp.social-iphone-1.8.4.zip) update. @viezel, can you also update the releases section?

**Comment by christianrockbryan** [comment]
Yes, 1.8.4 fixed the problem.  Thank you!
