### ISSUE TITLE
Build error on device, work fine on simulator with last Xcode

### ISSUE THREAD

**Issue by szanellato93** [viezel/TiSocial.Framework#159]
Today finally i resolve a problem incoming with the new Xcode version. When i tried to build my app on simulator, all work fine, but when i tried on my device i receive this error message:

[INFO] : Invoking xcodebuild
[ERROR] : *\* BUILD FAILED **
[ERROR] : The following build commands failed:
[ERROR] : Ld build/Intermediates/appBurger.build/Debug-iphoneos/appBurger.build/Objects-normal/arm64/appBurger normal arm64
[ERROR] : (1 failure)
2015-12-14T08:45:30.315Z | TRACE | titanium exited with exit code 1
2015-12-14T08:45:30.316Z | ERROR | Error: ti run exited with error code 1
at ChildProcess.<anonymous> (/Users/szanellato/.appcelerator/install/5.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:92:66)
at ChildProcess.emit (events.js:110:17)
at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
2015-12-14T08:45:30.317Z | TRACE | Sending exit signal to titanium process: 12752

resolved disable this module.

**Comment by vedransisic** [comment]
I'm having the same issue with iOS SDK 9.1 and 9.2.

**Comment by Cryde** [comment]
Hi

I experienced the same issue ...  
Any news on that ?

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.10.5
  Architecture                = 64bit
  # CPUs                      = 12
  Memory                      = 17179869184
Node.js
  Node.js Version             = 0.12.7
  npm Version                 = 2.11.3
Titanium CLI
  CLI Version                 = 5.0.6
Titanium SDK
  SDK Version                 = 5.2.0.GA
  SDK Path                    = /Users/developer/Library/Application Support/Titanium/mobilesdk/osx/5.2.0.GA
  Target Platform             = iphone
````

ping @viezel

**Comment by szanellato93** [comment]
i solved this issue but i don't remember how i hit it.. I remember only there are another component that go in conflict with TiSocial!

**Comment by vedransisic** [comment]
@szanellato93 

I believe I tried creating an empty project with just the TiSocial framework added as a module, and it still failed to build. I'll try again. 

Please let us know if you remember which module was the one that was conflicting.

**Comment by jstoyles** [comment]
I'm having the same issue. I updated my OS to 10.11.4. and I updated XCode to 7.3. I've tried rebuilding the module through XCode in about 10 different ways after playing with various build settings. I also tried using Ti SDK 4.1.1 all the way up to 5.2.1. No luck. I'm at a loss and very sad because this is one of my favorite Ti modules.

I'll be following this thread hoping for a resolution. I hope someone figures it out soon.

**Comment by jstoyles** [comment]
So I just downloaded the latest version which had version 1.8 in the dist folder (previously it had 1.8.4 as the latest). So I tried using this new 1.8 version and it worked like a charm. I'm not sure what was changed but I'm very grateful.

**Comment by skarakash** [comment]
@jstoyles latest version of what?

**Comment by drunnells** [comment]
I encountered the same error from the original post when building an app using 1.8.4. I even tried building the module myself instead of using the one in the dist dir without any luck. However, as jstoyles noticed, I CAN use the 1.8 version from dist and it seems to be working!

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.11.6
  Architecture                = 64bit
  # CPUs                      = 2
  Memory                      = 8589934592

Node.js
  Node.js Version             = 0.12.7
  npm Version                 = 2.11.3

Titanium CLI
  CLI Version                 = 5.0.8

Titanium SDK
  SDK Version                 = 5.3.0.GA
  SDK Path                    = /Users/drunnells/Library/Application Support/Titanium/mobilesdk/osx/5.3.0.GA
  Target Platform             = iphone
```

**Comment by CREATIVE-KAIZEN** [comment]
@drunnells:
I think it is connected with new version of Xcode. Same problem here with 1.8.4.
1.8 will compile but it will crash on iPad (activityPopover()).

**Comment by sandrolain** [comment]
Hi, to make it work also on arm64 I had to modify the module indicating SDK Titanium version 6.3.0 and removing references to TiUIButtonProxy.

**Comment by hansemannn** [comment]
This does not seem to be an issue anymore.
