### ISSUE TITLE
Titanium SDK 6.0.0 support?

### ISSUE THREAD

**Issue by netoramalho** [viezel/TiSocial.Framework#168]
Any plans to support the SDK 6+?
Thanks

**Comment by abdielou** [comment]
This module seems pretty stale...

**Comment by eemi2010** [comment]
Hi  here. Does this module works with SDK 6+ ?
Cheers.

**Comment by m1ga** [comment]
Did you try it :) ? 
Working fine with Ti 6.0.1.GA (tested the twitter connection). Since its an iOS module you don't need to recompile it for 6+

**Comment by frodfigu** [comment]
@m1ga Sure? My app crashes after Save an image

`var foto = $.fotoPerfil.toBlob();
var Social = require('dk.napp.social');
	Ti.API.info("Facebook available: " + Social.isFacebookSupported());
    Ti.API.info("Twitter available: " + Social.isTwitterSupported());
    Ti.API.info("SinaWeibo available: " + Social.isSinaWeiboSupported());
    if(Social.isActivityViewSupported()){
    	Social.activityView({
            text:"share like a king!",
            image:foto,
            //removeIcons:"print,sms,copy,contact,camera,mail",
            removeIcons:"sms",
            view: e.source //source button
        });
    }`

**Comment by frodfigu** [comment]
Solved for me...

http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Media-method-requestPhotoGalleryPermissions

**Comment by jsrsonu** [comment]
@m1ga - Am also using this module and am facing issue of crashing.I have a list view with image.When i try to click on save then it crashes without any error log. Cheked on iOS11.1 & 11.2. Any guess what could be the issue.Could you please help on this ? Thanks.

![screen shot 2018-02-21 at 2 36 53 pm](https://user-images.githubusercontent.com/36218484/36471463-851fbb8a-1714-11e8-87d2-5d30adf3a34b.png)
