### ISSUE TITLE
Crashes on click of save image

### ISSUE THREAD

**Issue by jsrsonu** [viezel/TiSocial.Framework#171]
When we click on save image of list view image then it crashes without any error log.Has anybody faced the same.?

**Comment by jabele** [comment]
I had the same issue and discovered I was missing a key in my tiapp.xml. You have to have both NSPhotoLibraryUsageDescription AND NSPhotoLibraryAddUsageDescription. The second one isn ew to iOS11:

<key>NSPhotoLibraryUsageDescription</key>
<string>Can we save to your library?</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Can we save to your library?</string>

**Comment by jsrsonu** [comment]
@jabele - Thanks a lot for quick answer.Its working now.
