### ISSUE TITLE
TiUtils isIOS6OrGreater unrecognized selector

### ISSUE THREAD

**Issue by ottopic** [viezel/TiSocial.Framework#177]
When I try to use it width SDK greater then 7.4.1 I get that error:

message = "+[TiUtils isIOS6OrGreater]: unrecognized selector sent to class 0x109614a10"

**Comment by klaudia-dogfish** [comment]
Any chance that we'll get a new build with fix in it? We want to upgrade our sdk to 8.0.0.GA asap.

**Comment by zarir** [comment]
Any update on this issue. Facing with Titanium sdk 8.0.0

**Comment by ottopic** [comment]
#181
